import clsx from "clsx";

import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { getServerAuthSession } from "~/server/auth";

import { TRPCReactProvider } from "~/trpc/react";

import { SocketIOProvider } from "~/context/socket";

import baseStyles from "~/styles/base_styles";

import Navbar from "./navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();
  return (
    <html lang="en">
      <body
        className={clsx(
          "font-sans",
          inter.variable,
          baseStyles.backgrounds.main,
          baseStyles.typography.colors.main,
        )}
      >
        <TRPCReactProvider>
          <Navbar>
            <SocketIOProvider session={session}>{children}</SocketIOProvider>
          </Navbar>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
