import clsx from "clsx";

import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { getServerAuthSession } from "~/server/auth";

import ContextProviders from "./providers";

import baseStyles from "~/styles/base_styles";
import Navbar from "~/app/navbar";

// this is a server-side provider definition so adding it here instead of in the `providers.tsx` file which is client-side rendered
import { NextGameRoomProvider } from "~/game_logic/game_room/client/next_provider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();
  return (
    <html lang="en">
      <body
        className={clsx(
          "flex h-dvh flex-col items-stretch",
          "font-sans",
          inter.variable,
          baseStyles.backgrounds.main,
          baseStyles.typography.colors.main,
        )}
      >
        <ContextProviders session={session}>
          <NextGameRoomProvider session={session}>
            <Navbar>{children}</Navbar>
          </NextGameRoomProvider>
        </ContextProviders>
      </body>
    </html>
  );
}
